[tool.poetry]
name = "calculator"
version = "0.1.0"
description = "Proyecto de empaquetamiento MLOps"
authors = ["Spydneo <jairoecalderon@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
